apiVersion: v1
data:
  storageclass.yaml: |
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: longhorn
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    reclaimPolicy: "Delete"
    volumeBindingMode: Immediate
    parameters:
      numberOfReplicas: "2"
      staleReplicaTimeout: "30"
      fromBackup: ""
      fsType: "ext4"
      dataLocality: "disabled"
      diskSelector: "nvme"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: longhorn-system-longhorn-release
    meta.helm.sh/release-namespace: longhorn-system
  labels:
    app.kubernetes.io/instance: longhorn-system-longhorn-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.6.0
    helm.sh/chart: longhorn-1.6.0
    helm.toolkit.fluxcd.io/name: longhorn-release
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: longhorn-storageclass
  namespace: longhorn-system
