allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-fast-dual
parameters:
  dataLocality: disabled
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  diskSelector: "fast"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
