allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-fast
parameters:
  dataLocality: disabled
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  diskSelector: "fast"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
