apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- cluster.yaml
- ceph-ingress.yaml
- replicapools.yaml
- storageclasss.yaml
- storageclasss-buckets.yaml
- object-store.yaml