---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: community-operator
      version: 0.11.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mongodb
  install:
    createNamespace: true
    crds: Skip
  upgrade:
    crds: Skip
  interval: 10m0s
  targetNamespace: mongodb-operator
  values:
    community-operator-crds:
      enabled: false
  