apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/rook/rook/v1.14.4/deploy/examples/common.yaml
- operator.yaml
- cluster.yaml

- ceph-ingress.yaml
- replicapools-nvme.yaml
#- replicapools-ssd.yaml
- object-store.yaml
#- storageclass-ssd.yaml
#- storageclass-nvme.yaml
#- storageclass-buckets.yaml

#- csi-metrics-service-monitor.yaml
#- exporter-service-monitor.yaml
#- externalrules.yaml
# - keda-rgw.yaml
#- localrules.yaml
#- service-monitor.yaml