apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: object-store
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
    deviceClass: nvme
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
    deviceClass: nvme
  preservePoolsOnDelete: true
  gateway:
    sslCertificateRef:
    port: 8080
    # securePort: 443
    instances: 2
