---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: flux-system
spec:
  chart:
    spec:
      chart: reloader
      version: 1.0.119
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: stakater
  install:
    createNamespace: true
  interval: 10m0s
  targetNamespace: reloader