apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webtop-simon
  namespace: webtop
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: webhook-backend
    kind: ClusterSecretStore
  target:
    name: webtop-simon
    template:
      data:
        username: "{{ .username | toString }}"
        password: "{{ .password | toString }}"
  data:
  - secretKey: username
    remoteRef:
      key: webtop-simon-username
  - secretKey: password
    remoteRef:
      key: webtop-simon-password