---
apiVersion: v1
kind: Namespace
metadata:
  name: webtop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simon-home
  namespace: webtop
spec:
  storageClassName: ceph-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simon-data
  namespace: webtop
spec:
  storageClassName: ceph-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi