---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: eck-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: elastic
      version: 2.15.0
  install:
    crds: Create
    createNamespace: true
  interval: 10m0s
  targetNamespace: elastic-system
