apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: flux-loki-bucket
  namespace: flux-system
spec:
  bucketName: ${AWS_BUCKET_NAME}
  storageClassName: rook-ceph-bucket
  additionalConfig:
    maxObjects: "100000"
    maxSize: "50G"
