apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: webhook-backend
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials
    template:
      data:
        admin-user: "{{ .username | toString }}"
        admin-password: "{{ .password | toString }}"
  data:
  - secretKey: password
    remoteRef:
      key: grafana-password
      property: turingpi
  - secretKey: username
    remoteRef:
      key: grafana-username
      property: turingpi