apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- grafana-admin-credentials-external.yaml
- kube-prometheus-stack-release.yaml
- prometheus-ingress.yaml
- grafana-ingress.yaml
- loki-release.yaml
# - loki-stack-release.yaml
- promtail-release.yaml