---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki
      version: 6.6.2
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    crds: Create
    createNamespace: true
  upgrade:
    crds: CreateReplace
  interval: 1m0s
  targetNamespace: monitoring
  values:
    gateway:
      enabled: false
    singleBinary:
      replicas: 1
      persistence:
        size: 20Gi
        storageClass: ceph-ssd
    loki:
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
        
      schemaConfig:
        configs:
          - from: "2024-06-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
      readinessProbe:
        httpGet:
          port: 3100
      querier:
        multi_tenant_queries_enabled: true
        max_concurrent: 2
      ingester:
        chunk_encoding: snappy
      tracing:
        enabled: true
      ruler:
        alertmanager_url: http://prometheus-alertmanager:9093
    deploymentMode: SingleBinary
    chunksCache:
      # default is 500MB, with limited memory keep this smaller
      writebackSizeLimit: 10MB
    ingress:
      enabled: true
      annotations: 
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
      ingressClassName: traefik
      hosts:
        - loki.${clusterdomain:=undefined}
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
        