---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki
      version: 6.6.3
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    crds: Create
    createNamespace: true
  upgrade:
    crds: CreateReplace
  interval: 1m0s
  targetNamespace: monitoring
  values:
    gateway:
      enabled: false
    singleBinary:
      replicas: 0
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: s3
        bucketNames: 
          chunks: ${AWS_BUCKET_NAME} 
          ruler:  ${AWS_BUCKET_NAME} 
          admin:  ${AWS_BUCKET_NAME} 
        s3:
#          s3: http://${AWS_ACCESS_KEY_ID}:${AWS_SECRET_ACCESS_KEY}@rook-ceph-rgw-object-store.rook-ceph.svc.cluster.local:8080/
          endpoint: rook-ceph-rgw-object-store.rook-ceph.svc:8080
          secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
          accessKeyId: ${AWS_ACCESS_KEY_ID}
          s3ForcePathStyle : true
          insecure: true
      schemaConfig:
        configs:
          - from: "2024-06-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: index_
              period: 24h
      readinessProbe:
        httpGet:
          port: 3100
      querier:
        multi_tenant_queries_enabled: true
        max_concurrent: 2
      ingester:
        chunk_encoding: snappy
      tracing:
        enabled: true
      ruler:
        alertmanager_url: http://prometheus-alertmanager:9093
    deploymentMode: SimpleScalable
    chunksCache:
      # default is 500MB, with limited memory keep this smaller
      writebackSizeLimit: 10MB
    ingress:
      enabled: true
      annotations: 
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
      ingressClassName: traefik
      hosts:
        - loki.${clusterdomain:=undefined}
    backend:
      replicas: 3
    read:
      replicas: 3
    write:
      replicas: 3
      
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
        