apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: traefik
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - traefik
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - traefik
  podMetricsEndpoints:
    - port: metrics