apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webhook-token
  namespace: flux-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: webhook-backend
    kind: ClusterSecretStore
  target:
    name: webhook-token
    template:
      data:
        token: "{{ .token | toString }}"
  data:
  - secretKey: token
    remoteRef:
      key: github-webhook-turing