apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-data
  namespace: traefik
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-fast
  resources:
    requests:
      storage: 500Mi