apiVersion: v1
data:
  promtail.yaml: |-
    server:
      log_level: info
      log_format: logfmt
      http_listen_port: 3101
    clients:
      - url: http://loki-write.monitoring:3100/loki/api/v1/push
    positions:
      filename: /accesslogs/positions.yaml
    scrape_configs:
      - job_name: traefik
        static_configs:
        - targets:
            - localhost
          labels:
            app: traefik
            job: traefik/traefik
            component: accesslog
            __path__: /accesslogs/*.log
    tracing:
      enabled: false
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: traefik