---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-secrets
      version: 0.9.17
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  install:
    crds: Skip
  upgrade:
    crds: CreateReplace
  interval: 10m0s
  targetNamespace: external-secrets
  values:
    installCRDs: false
