---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: flux-system
spec:
  chart:
    spec:
      chart: csi-driver-nfs
      version: v4.7.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
  install:
    crds: Create
    createNamespace: true
  interval: 1m0s
  targetNamespace: kube-system
  upgrade:
    crds: CreateReplace

