apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-diskstation
provisioner: nfs.csi.k8s.io
parameters:
  server: diskstation.stiil.local
  share: /volume1/kubernetes-nfs/
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1