## https://github.com/external-secrets/external-secrets/tree/main/config/crds/bases
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: crds-external-secrets
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/external-secrets/external-secrets.git
  ref:
    tag: v0.9.13 
  ignore: |
    # exclude all
    /*
    # path to crds
    !/deploy/crds/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds-external-secrets
  namespace: flux-system
spec:
  interval: 30m
  prune: false
  sourceRef:
    kind: GitRepository
    name: crds-external-secrets
  healthChecks:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: acraccesstokens.generators.external-secrets.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: clusterexternalsecrets.external-secrets.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: clustersecretstores.external-secrets.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: ecrauthorizationtokens.generators.external-secrets.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: externalsecrets.external-secrets.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: fakes.generators.external-secrets.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: gcraccesstokens.generators.external-secrets.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: passwords.generators.external-secrets.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: pushsecrets.external-secrets.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: secretstores.external-secrets.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: vaultdynamicsecrets.generators.external-secrets.io