apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: crds-gateway-api
  namespace: flux-system
spec:
  interval: 30m
  timeout: 2m
  url: https://github.com/kubernetes-sigs/gateway-api.git
  ref:
    tag: v1.0.0
  ignore: |
    # exclude all
    /*
    # path to crds
    !/config/crd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds-gateway-api
  namespace: flux-system
spec:
  interval: 30m
  timeout: 2m
  prune: false
  sourceRef:
    kind: GitRepository
    name: crds-gateway-api
    namespace: flux-system
  healthChecks:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: gatewayclasses.gateway.networking.k8s.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: gateways.gateway.networking.k8s.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: httproutes.gateway.networking.k8s.io
#  - apiVersion: apiextensions.k8s.io/v1
#    kind: CustomResourceDefinition
#    name: referencegrants.gateway.networking.k8s.io