apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: crds-metallb
  namespace: flux-system
spec:
  interval: 30m
  timeout: 2m
  url: https://github.com/metallb/metallb.git
  ref:
    tag: v0.14.7
  ignore: |
    # exclude all
    /*
    # path to crds
    !/config/crd/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds-metallb
  namespace: flux-system
spec:
  interval: 30m
  prune: false
  sourceRef:
    kind: GitRepository
    name: crds-metallb
    namespace: flux-system
  healthChecks:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: bfdprofiles.metallb.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: bgpadvertisements.metallb.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: communities.metallb.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: ipaddresspools.metallb.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: l2advertisements.metallb.io