---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds-base
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./crds/base
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
