---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elastic-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./elastic-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
