---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m
  path: ./external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crds-external-secrets
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: external-secrets-external-secrets
    namespace: external-secrets
  - apiVersion: apps/v1
    kind: Deployment
    name: external-secrets-external-secrets-cert-controller
    namespace: external-secrets
  - apiVersion: apps/v1
    kind: Deployment
    name: external-secrets-external-secrets-webhook
    namespace: external-secrets
  - apiVersion: v1
    kind: Service
    name: external-secrets-external-secrets-webhook
    namespace: external-secrets
  postBuild:
    substitute:
      var_substitution_enabled: "true"
    substituteFrom:
      - kind: Secret
        name: clusterconfig
        optional: true
---