apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crds.yaml
- cluster-base.yaml
- metallb.yaml
- external-secrets.yaml
- cert-manager.yaml
- csi-driver-nfs.yaml
- traefik.yaml
- flux-webhook.yaml
- elastic-system.yaml
- monitoring.yaml
- rook.yaml
- reloader.yaml
- uptime-kuma.yaml
- dashboard.yaml
- jenkins.yaml

## Removed elements:
#- longhorn.yaml