---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-chart
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./metallb/chart
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: l2advertisements.metallb.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: ipaddresspools.metallb.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: bfdprofiles.metallb.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: communities.metallb.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: bgpadvertisements.metallb.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
  
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-post
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./metallb/post
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: metallb-chart
  healthChecks:
  - apiVersion: metallb.io/v1beta1
    kind: IPAddressPool
    name: picluster-pool
    namespace: metallb-system
  - apiVersion: metallb.io/v1beta1
    kind: L2Advertisement
    name: picluster
    namespace: metallb-system
