---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crds-metallb
  healthChecks:
  - apiVersion: metallb.io/v1beta1
    kind: IPAddressPool
    name: picluster-pool
    namespace: metallb-system
  - apiVersion: metallb.io/v1beta1
    kind: L2Advertisement
    name: picluster
    namespace: metallb-system
