---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mongodb-operator
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m
  path: ./mongodb-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: mongodb-kubernetes-operator
    namespace: mongodb-operator
  dependsOn:
    - name: crds-base

