---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mongodb-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./mongodb-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crds-external-secrets

