---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m
  path: ./monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system-additions-rook
  postBuild:
    substitute:
      var_substitution_enabled: "true"
    substituteFrom:
      - kind: Secret
        name: clusterconfig
        optional: false
      - kind: Secret
        name: flux-loki-bucket
        optional: false
      - kind: Secret
        name: flux-loki-bucket-name
        optional: false
---