---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m
  path: ./rook
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crds-rook
  postBuild:
    substitute:
      var_substitution_enabled: "true"
    substituteFrom:
      - kind: Secret
        name: clusterconfig
        optional: true
  healthChecks:
  - apiVersion: v1
    kind: ConfigMap
    name: rook-ceph-operator-config
    namespace: rook-ceph
  - apiVersion: apps/v1
    kind: Deployment
    name: rook-ceph-operator
    namespace: rook-ceph
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: rook-ceph-system
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    name: rook-ceph-system
  - apiVersion: v1
    kind: ServiceAccount
    name: rook-ceph-system
    namespace: rook-ceph