---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: webtop
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m
  path: ./webtop
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: webtop-simon
    namespace: webtop
  - apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    name: webtop-simon
    namespace: webtop
  - apiVersion: v1
    kind: Service
    name: webtop-simon
    namespace: webtop
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: webtop-simon
    namespace: webtop
  postBuild:
    substitute:
      var_substitution_enabled: "true"
    substituteFrom:
      - kind: Secret
        name: clusterconfig
        optional: true

