apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dockercred
  namespace: jenkins
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: webhook-backend
    kind: ClusterSecretStore
  target:
    name: dockercred
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfig | toString }}"
  data:
  - secretKey: dockerconfig
    remoteRef:
      key: jenkins-dockercred