apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: email-secret
  namespace: jenkins
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: webhook-backend
    kind: ClusterSecretStore
  target:
    name: email-secret
    template:
      metadata:
        labels:
          "jenkins.io/credentials-type": "usernamePassword"
          "jenkins.io/credentials-scope": "global"
        annotations:
          "jenkins.io/credentials-description": "robot email Account"
      data:
        username: "{{ .username | toString }}"
        password: "{{ .password | toString }}"
  data:
  - secretKey: username
    remoteRef:
      key: robot-email-username
  - secretKey: password
    remoteRef:
      key: robot-email-password