apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token-secret
  namespace: jenkins
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: webhook-backend
    kind: ClusterSecretStore
  target:
    name: github-token-secret
    template:
      metadata:
        labels:
          "jenkins.io/credentials-type": "secretText"
          "jenkins.io/credentials-scope": "global"
        annotations:
          "jenkins.io/credentials-description": "Burads GitHub Account Token"
      data:
        text: "{{ .password | toString }}"
  data:
  - secretKey: password
    remoteRef:
      key: github-password-token