---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: flux-system
spec:
  chart:
    spec:
      chart: jenkins
      version: 5.1.23
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jenkins
  interval: 1m0s
  targetNamespace: jenkins
  values:
    controller:
      JCasC:
        configScripts:
          email-ext: |-
            unclassified:
              email-ext:
                adminRequiredForTemplateTesting: false
                allowUnregisteredEnabled: false
                charset: "UTF-8"
                debugMode: false
                defaultBody: |-
                  $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:
                  Check console output at $BUILD_URL to view the results.
                defaultContentType: "text/plain"
                defaultRecipients: "${githubemail:=undefined}"
                defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
                defaultSuffix: "@gmail.com"
                defaultTriggerIds:
                - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
                mailAccount:
                  credentialsId: "email-secret"
                  smtpHost: "send.one.com"
                  smtpPort: "465"
                  useSsl: true
                maxAttachmentSize: -1
                maxAttachmentSizeMb: -1
                precedenceBulk: false
                watchingEnabled: false
          github: |-
            unclassified:
              gitHubConfiguration:
                apiRateLimitChecker: ThrottleForNormalize
              gitHubPluginConfig:
                configs:
                - credentialsId: "github-token-secret"
                  name: "SimonStiil Org"
                hookUrl: "https://jenkins.${clusterdomain:=undefined}/github-webhook/"
              scmGit:
                globalConfigEmail: "${githubemail:=undefined}"
                globalConfigName: "SimonStiil"
          ldap-settings: |-
            jenkins:
              securityRealm:
                ldap:
                  configurations:
                  - groupMembershipStrategy:
                      fromUserRecord:
                        attributeName: "memberOf"
                    groupSearchBase: "cn=groups"
                    groupSearchFilter: "(& (cn={0}) (objectClass=posixGroup))"
                    inhibitInferRootDN: false
                    managerDN: "uid=svc-jenkins,cn=users,${ldapclusterdomain:=undefined}"
                    managerPasswordSecret: $${ldap-secret-password}
                    rootDN: "${ldapclusterdomain:=undefined}"
                    server: "ldaps://diskstation.${topleveldomain:=undefined}"
                    userSearchBase: "cn=users"
                  disableMailAddressResolver: false
                  disableRolePrefixing: true
                  groupIdStrategy: "caseInsensitive"
                  userIdStrategy: "caseInsensitive"
          pipeline-library: |-
            unclassified:
              globalLibraries:
                libraries:
                - defaultVersion: "main"
                  name: "pipeline-library"
                  retriever:
                    modernSCM:
                      scm:
                        github:
                          configuredByUrl: true
                          credentialsId: "github-login-secret"
                          id: "2140d28d-d704-4e67-8119-41a227e893b5"
                          repoOwner: "SimonStiil"
                          repository: "pipeline-library"
                          repositoryUrl: "https://github.com/SimonStiil/pipeline-library"
                          traits:
                          - gitHubBranchDiscovery:
                              strategyId: 1
                          - gitHubPullRequestDiscovery:
                              strategyId: 1
                          - gitHubForkDiscovery:
                              strategyId: 1
                              trust: "gitHubTrustPermissions"
      additionalExistingSecrets:
      - keyName: password
        name: ldap-secret
      additionalPlugins:
      - ldap
      - http_request
      - pipeline-maven
      - pipeline-utility-steps
      - pipeline-stage-view
      - pipeline-github
      - github-api
      - github-branch-source
      - github-checks
#      - github-autostatus
      - job-dsl
      - basic-branch-build-strategies
      - email-ext
      - mailer
      - timestamper
      - kubernetes-credentials-provider
      - credentials-binding
      - generic-webhook-trigger
      ingress:
        annotations:
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
        apiVersion: networking.k8s.io/v1
        enabled: true
        hostName: jenkins.${clusterdomain:=undefined}
        ingressClassName: traefik
      jenkinsAdminEmail: robot@${topleveldomain:=undefined}
      jenkinsUrl: https://jenkins.${clusterdomain:=undefined}
      resources:
        limits:
          cpu: 4000m
          memory: 8192Mi
        requests:
          cpu: 200m
          memory: 2048Mi
    persistence:
      storageClass: rook-ceph-block-nvme
    rbac:
      create: true
      readSecrets: true
