apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ldap-secret
  namespace: jenkins
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: webhook-backend
    kind: ClusterSecretStore
  target:
    name: ldap-secret
    template:
      data:
        password: "{{ .password | toString }}"
  data:
  - secretKey: password
    remoteRef:
      key: jenkins-ldap-password