apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-tester
  namespace: jenkins-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: jenkins-tester
  namespace: jenkins
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-tester
  namespace: jenkins
