apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins-squid
resources:
- namespace.yaml
- squid-deployment.yaml
- mitm-cert.yaml
generatorOptions:
 disableNameSuffixHash: true
configMapGenerator:
- name: squid-config
  files:
  - squid.conf