---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      version: v0.14.3
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metallb
  install:
    crds: Skip
  interval: 10m0s
  targetNamespace: metallb-system
  values:
    crds:
      enabled: false