---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teleport
  namespace: flux-system
spec:
  chart:
    spec:
      chart: teleport-cluster
      reconcileStrategy: ChartVersion
      version: 16.1.6
      sourceRef:
        kind: HelmRepository
        name: teleport
  install:
    crds: Skip
  interval: 10m0s
  timeout: 5m0s
  targetNamespace: teleport
  values:
    clusterName: teleport.stiil.dk
    proxyListenerMode: multiplex
    highAvailability:
      certManager:
        enabled: true
        addCommonName: true
        issuerName: letsencrypt-cloudflare-issuer
        issuerKind: ClusterIssuer
    service:
      type: ClusterIP
    ingress:
      enabled: true
      spec:
        ingressClassName: traefik
    operator:
      enabled: true
    proxy:
      annotations: 
        ingress:
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
        service:
          traefik.ingress.kubernetes.io/service.serversscheme: https
          traefik.ingress.kubernetes.io/service.serverstransport: teleport-allowselfsigned@kubernetescrd
    auth:
      persistence:
        enabled: true
        storageClassName: ceph-nvme