apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- cluster-stiil-ca-external.yaml
- cloudflare-api-token-external.yaml
- cert-manager-release.yaml
- cloudflare-issuer.yaml
- cloudflare-staging-issuer.yaml
- stiil-issuer.yaml
